title: Meira German | מאירה דבורה גרמן
author: Gabriel Natenshon, João Neto
email: gnatenshon@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
disclaimer: >-
  lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

user:
  phone: +972 54-366-5576
  email: meira.german35@gmail.com

social:
  twitter:
  facebook:
  instagram:
  github:
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
